name: Publich to gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
    uses: actions/setup-node@v1
    with:
      node-version: '12.x'
    - remote_theme: pages-themes/cayman@v0.2.0
    plugins:
    - jekyll-remote-theme